arm-none-eabi-ar -r "thedrv" ./DeviceDrivers/Src/MF_RC522.o ./DeviceDrivers/Src/ctiic.o ./DeviceDrivers/Src/devAT24C02.o ./DeviceDrivers/Src/devBY8301.o ./DeviceDrivers/Src/devDelay.o ./DeviceDrivers/Src/devHMIScreen.o ./DeviceDrivers/Src/devKey.o ./DeviceDrivers/Src/devLed.o ./DeviceDrivers/Src/devLtdc.o ./DeviceDrivers/Src/devSdram.o ./DeviceDrivers/Src/devUsart.o ./DeviceDrivers/Src/devW25Qxx.o ./DeviceDrivers/Src/emuI2C.o ./DeviceDrivers/Src/ft5206.o ./DeviceDrivers/Src/ftl.o ./DeviceDrivers/Src/malloc.o ./DeviceDrivers/Src/nand.o ./DeviceDrivers/Src/sys.o ./DeviceDrivers/Src/touch.o 


 
 















